# configmap.r10k-config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: devpod
  name: r10k-config
data:
  r10k.yaml: |
    ---
    :cachedir: '/var/cache/r10k'
    :sources:
      :base:
        remote: 'git@github.com:AAInternal/puppet-control-repo.git'
        basedir: '/etc/puppetlabs/code/environments'
